trigger:
- master

pool:
  vmImage: 'ubuntu-22.04'

steps:
- task: katalonTask@1
  inputs:
    version: '8.6.8'
    executeArgs: '-testSuitePath="Test Suites/New Test Suite" -browserType="Chrome" -apiKey=$(katalon_api_key) --config -webui.autoUpdateDrivers=true'
    xvfbConfiguration: '-s "-screen 0 1024x768x24"'
  env:
    JAVA_HOME: $(JAVA_HOME_8_X64)
    PATH: $(JAVA_HOME_8_X64)/bin:$(PATH)

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/
