trigger:
- master

pool:
  # vmImage: 'ubuntu-22.04'
  vmImage: macos-latest

steps:
# - task: CmdLine@2
#   inputs:
#     script: |
#       echo "Installing Java" 
#       sudo apt update
#       sudo apt install openjdk-8-jre -y
#       sudo update-java-alternatives -l
#       sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/bin/java
#       echo "Java Version Installed is"
#       java -version
#       echo "Install Complete"
#       export JAVA_HOME_8_X64="/usr/lib/jvm/java-8-openjdk-amd64"
#       echo $JAVA_HOME_8_X64
#       export HELLO="Hello"
#       echo "Hello should print here: $HELLO"

# - task: CmdLine@2
#   env:
#       JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64
#       PATH: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:$(PATH)
#   inputs:  
#     script: |
#       java -version
#       echo "Hello should not print here: $HELLO"
- task: NodeTool@0
  inputs:
    versionSpec: '16.20.0'
    displayName: 'Install Node.js'

- task: katalonTask@1
  inputs:
    version: '9.3.0'
    executeArgs: '-testSuitePath="Test Suites/New Test Suite" -browserType="Chrome" -apiKey=$(katalon_api_key)'
  #   xvfbConfiguration: '-s "-screen 0 1024x768x24"'
  # env:
  #   JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64
  #   PATH: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin:$(PATH)

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/
