trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
- task: CmdLine@2
  inputs:
    script: |
      sudo apt-get update
      sudo apt-get install at-spi2-core
      sudo apt-get install xvfb
      sudo apt-get install apt-utils
      sudo apt-get install wget
      sudo apt-get install unzip
      sudo apt-get install curl
      sudo apt-get install gosu
      sudo apt-get install psmisc
      sudo apt-get install libfontconfig
      sudo apt-get install libfreetype6
      sudo apt-get install xfonts-cyrillic
      sudo apt-get install xfonts-scalable
      sudo apt-get install fonts-liberation
      sudo apt-get install fonts-ipafont-gothic
      sudo apt-get install fonts-wqy-zenhei
      sudo apt-get install fonts-tlwg-loma-otf
      sudo apt-get install ttf-ubuntu-font-family
- task: katalonTask@1
  inputs:
    version: '8.6.8'
    executeArgs: '-testSuitePath="Test Suites/New Test Suite" -browserType="Chrome" -apiKey=$(katalon_api_key) --config -webui.autoUpdateDrivers=true'
    xvfbConfiguration: '--auto-servernum -a -n 0 -s "-screen 0 1024x768x24"'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'JUnit Report' 
    targetPath: report/
