name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Katalon Run 1
      run:  'docker run -t -v "$(pwd)":/tmp/project katalonstudio/katalon:10.1.0 katalonc.sh -projectPath=/tmp/project -noSplash -testSuitePath="Test Suites/New Test Suite" -apiKey=${{ secrets.SECRET_KEY }} -browserType="Chrome" --config -webui.autoUpdateDrivers=true'
