name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Katalon Run 1
      run:  'docker run -t --rm -v "$(pwd)":/tmp/project katalonstudio/katalon:9.6.0 google-chrome --headless'
